### ISSUE TITLE
Player.units or map?

### ISSUE THREAD

**Issue by Rocketknight1** [aparkins/pydip#2]
Hey! First off, thanks for making this! I'm tinkering with an AI project revolving around Diplomacy and this library looks really useful.

I found the entry points you mentioned in the other issue, and got a basic turn loop working, but there's one thing I'm confused about. Player objects have lists of Unit objects, but the map also has a dict mapping country name strings to Unit objects, which seems like the same information being stored in two places. All the other functions seem to mostly operate on the map, and I'm unclear on how exactly to handle the Player.units lists - should I ignore them? If not, should I manually update them at the end of each turn, or is there a function to handle this that I missed?

**Comment by aparkins** [comment]
Glad to hear you've found the project helpful!

So I'm not seeing exactly where you're seeing the mapping of strings to list of Units being stored in the map, unless you're talking about `pydip.map.predefined.vanilla_dip::generate_starting_player_units()`? That's just a helper function intended to enumerate the initial positions for the various players on the vanilla diplomacy board.

This might just be reiterating what I said in the other issue to a certain extent, but it should be said that this library is very much intended to JUST perform the adjudication logic of Diplomacy. In other words: given the layout of a `Map` (which is just a graph showing how territories are connected to each other) and `Commands` issued to `Units` on that `Map`, the library will determine what the new game state should be.

My intention was to use this as the backing game logic for a web-app game, but my intention was always that it would be the game project that would be responsible for figuring out how to track the long-running state. That way I wouldn't be coupling this library to working with a database, or requiring any enthusiastic AI researchers to deal with my goofy custom game logic to make use of the code. 😃 But that does mean your project will need to do some elbow-grease and design work to determine how you want to track the game between turns and phases of a turn. 😦 

If it's helpful, you can check the beginnings of the web-app game code [here](https://github.com/aparkins/verbose-carnival). Specifically, you might look into the logic wrapping [resolving turns](https://github.com/aparkins/verbose-carnival/tree/master/dip_server/dip_platform/logic/game/resolution). There's a bit of boilerplate in those files, but the gist of what's going on should be relatively straight-forward. Happy to give some clarifications if needed, though. 🙂

**Comment by aparkins** [comment]
Ah, I see what you mean. Yes, the `resolve` functions don't directly output new game states, but more like instructions for how to modify an existing game state. You'll definitely want to do manual updates in your logic. Sorry for the inconvenience!
