### ISSUE TITLE
Self dislodgement tests fail

### ISSUE THREAD

**Issue by lstrobel** [aparkins/pydip#4]
I'm using your wonderful library in a project of mine, but when I run the tests you've written, those related to self-dislodgement rules seem to fail. Specifically, the engine seems to allow self-dislodgement. 

![image](https://user-images.githubusercontent.com/12887715/64642765-eb395f80-d3c3-11e9-9be0-b6685dd1b8c7.png)

**Comment by lstrobel** [comment]
Unable to reproduce in a standalone environment. It was something on my side

**Comment by aparkins** [comment]
Hope you were able to figure out your issue! Thanks for using the library, and glad to hear it's been helpful to you! :)
